<template>
  <div class="page-basic">
    <BlockBasicText :data="basicContent" />
  </div>
</template>

<script lang="ts">
    import Vue from 'vue'
    import BlockBasicText from '@/components/blocks/BlockBasicText.vue'

	export default Vue.extend({
		name: 'BasicPage',

		components: {
            BlockBasicText,
		},

		data() {
			return {
                page: 'basic-page',
                basicContent: {
                    title: 'Finance Lobby Privacy Policy',
                    text: `
                        <p>Last Updated: September 23, 2020</p>

                        <p>This notice describes the Privacy Policy of Finance Lobby, LLC (“Finance Lobby”) and is effective as of the date Last Updated. By accessing and using this website, you are consenting to and accepting the terms, conditions and practices described in this Privacy Policy.</p>

                        <p>We may collect information that identifies you individually or allows us to contact you directly (personal information). We may ask for or collect personal information when you create an account, request a service, subscribe to communications, respond to a survey, or engage in some other activity on our site. We may ask you for contact information such as your name, address, telephone number, and email address. We may ask you for geolocation information, or it may be automatically provided by your browser or device. If you do not want the website to collect geolocation information, you can turn off location services in your browser or device.</p>

                        <p>When you visit our website, to the extent permitted by law and applicable agreements, we may collect site visitation data information such as your IP addresses, IMEI/UDID, MAC address, browser type, operating system, pages visited on our site, referring and exit pages, the dates and times of the visits, and the terms that you use in searches on our websites. We may partner with certain third parties to collect and analyze some of this information for permitted business purposes. Finance Lobby may use this information to improve site administration, provide general statistics, or for any other purpose permitted by law. This information may be linked with other personal information to the extent permitted by law.</p>

                        <p>We may use the collected personal information to fulfill and provide the services, or information, you request from us, marketing and advertising our products and services, conducting research and analysis, or for other lawful business purposes. This may include sending information that you have requested or contacting you about products and services that you have purchased.  This may include sharing certain information with other Finance Lobby subscribers in the course of providing our services, including browsing and matching services.  Finance Lobby may contact you via the website or through your provided email address to provide our services, and to market services which may be of interest to you.</p>

                        <p>We may combine the personal and other information we receive from one source with information we receive from other sources. For example, we may combine personal information collected through our websites with other information that we collect about you in other contexts—such as our communications with you via email or phone, or your customer service records. We also may combine your personal information with information that we obtain from third parties.</p>

                        <p>We may use contact databases obtained from third parties for marketing purposes.</p>

                        <p>If you do not opt-out of communications from us, we may send you marketing notices including promotions of our products and services. Finance Lobby or a third-party provider will process opt-out requests within a reasonable time. </p>

                        <p>We may employ third parties to perform functions on our behalf including processing credit card payments and chargebacks, and providing customer service. We may provide collected personal information to third parties as needed to perform their functions.</p>

                        <p>Finance Lobby sites and promotional emails may use technologies including trackers, cookies, web beacons, clear gifs, action tags, and/or location-based services, which may result in the collection of personal information. Finance Lobby may use this information to track system usage, to assist in tracking and analyzing advertising effectiveness, including for email campaigns, to count and recognize site visitors, to personalize your experience, to conduct general analysis and research, to personalize advertising, or for any other purpose permitted by law. Our sites may not be designed to respond to "do not track" requests from browsers.</p>

                        <p>We may release account and other personal information when required by law, regulation, court order, subpoena or other legal process, or when we believe release is appropriate to comply with the law; to enforce or apply our conditions of use and other agreements; or protect the rights, property, or safety of Finance Lobby, our users, or others. </p>

                        <p>Finance Lobby does not knowingly collect personal information from children under the age of 18. </p>

                        <p>We use cookies to help us improve, promote, and protect our services. By using the site, you agree to our cookie policy. When you visit our site, a cookie may be saved on your computer (if your computer accepts cookies), and if you return to the site the cookie may be read. We use cookies to help us collect the site visitation data described above and in some cases to deliver specialized content. A cookie is a small data file that certain websites write to your hard drive when you visit them. A cookie file can contain information such as a user ID that the site uses to track the pages you've visited, but the only personal information a cookie can contain is information you supply yourself. A cookie can't read data off your hard disk or read cookie files created by other sites. Some parts of our website may use cookies to track user traffic patterns. We do this in order to determine the usefulness of our website information to our users and to see how effective our navigational structure is in helping users reach that information. We may use this information for any purpose permitted by law.</p>

                        <p>Users can control the use of cookies at the individual browser level. If you prefer not to receive cookies on our website, you can set your browser to warn you before accepting cookies and refuse the cookie when your browser alerts you to its presence. You can also refuse all cookies by turning them off in your browser. Refusing cookies or turning them off may have unpredictable effects on the functionality of the site.</p>

                        <p>Our website may contain links to other websites. If you use these links, you will leave our website. When you access a non-Finance Lobby website, even one that may contain the Finance Lobby logos, please be aware that we do not control the content and we are not responsible for the privacy practices of that site. This Privacy Policy does not cover the information practices of those websites linked to our website, which are outside of our control.</p>

                        <p>Our website may include social media features such as the Facebook "Like" button, or the "Share This" button. Social media features on this site collect standard information such as your IP address, the page you are visiting on our website, and may use cookies. Social media functions provided by a third party are governed by the party’s privacy policy.</p>

                        <p>We use reasonable physical, technical and administrative security measures to protect the personal information that we collect, however, we cannot guarantee and do not warrant or represent, that all information will be protected against loss, misuse, or unauthorized access by third parties. By your use of this site, you acknowledge that no Internet data transmission and no means of electronic or physical data storage can be guaranteed as secure from such incidents and agree that you will not hold us responsible for any breach of security. You acknowledge that we cannot guarantee the security of any information you transmit to us and you use this site at your own risk.</p>

                        <p>We may retain your information for as long as your account is active or as needed to provide you services, comply with our legal obligations, resolve disputes, and enforce our agreements.</p>

                        <p>We may share personal information in the event of a corporate sale, merger, acquisition, dissolution, or similar event.</p>

                        <h4>CALIFORNIA PRIVACY RIGHTS:</h4><p>If you are a resident of California, Section 1798.83 of the California Civil Code gives you the right to request certain information with respect to the types of personal information we share with third parties for direct marketing purposes by such third party and the identities of the third parties with whom we have shared such information during the immediately preceding calendar year. To request a copy of the information disclosure, please contact Finance Lobby toll free at <a href="tel:855-415-6229 (855-41LOBBY)">855-415-6229 (855-41LOBBY)</a>.  Additionally, please see our California Consumer Privacy Act Disclosures, below, concerning rights you may have under the California Consumer Privacy Act.  In the event of any inconsistency between the California Consumer Privacy Act Disclosures on one hand and the Terms and Conditions and/or Privacy Policy on the other hand, the California Consumer Privacy Act Disclosures control.</p>

                        <p>Special note for individuals outside the United States: The personal and other information that is subject to this policy (including the information collected on Finance Lobby sites from visitors outside the United States) is collected and controlled by Finance Lobby, LLC in the United States. Finance Lobby’s principal office is in New York, New York. You agree that your information will be processed in the United States for the purposes described herein. As described above, Finance Lobby also may subcontract the processing of your data to, or otherwise share your data with, Finance Lobby affiliates, authorized distributors, trusted service providers, and trusted business partners in the United States or countries other than your country of residence. The data-protection laws in these countries may be different from, and less stringent than, those in your country of residence. You expressly consent to such transfer and processing.</p>

                        <p>Any dispute over privacy is subject to this Policy and our Terms & Conditions, including limitations on damages, limitations on warranties, mandatory arbitration, and application of the law of the state of New York. Our Privacy Policy and Terms & Conditions may change from time to time. Our current Privacy Policy applies to all information that we have or may collect in the future about you and your account.</p>

                        <p>We may from time to time update this Privacy Policy in our sole discretion. When we make these updates, we will change the "last updated" date listed at the top of the Policy.</p>

                        <h4>CALIFORNIA CONSUMER PRIVACY ACT DISCLOSURES</h4>

                        <p>These California Consumer Privacy Act disclosures supplement the Finance Lobby Privacy Policy and is effective as of the date Last Updated.   In the event of any inconsistency between the California Consumer Privacy Act Disclosures on one hand and the Terms and Conditions and/or Privacy Policy on the other hand, the California Consumer Privacy Act Disclosures control.  These disclosures are required by the California Consumer Privacy Act of 2018 as amended and may be required by other applicable state laws.</p>

                        <p>Categories of personal information collected:  The personal information that Finance Lobby collects or has collected from consumers in the preceding 12 months are in the following categories.</p>

                        <ul>
                            <li>1. Identifiers: personal names, postal addresses, billing addresses, phone numbers, email addresses, IP addresses, social media addresses.  The purposes of collecting this category of information are: to provide you with the products or services you requested; to provide browsing and matching services to other users; to help improve our products and services; to provide follow-up communications regarding your purchases; to market additional products and services you may be interested in; comply with legal obligations; and to prevent fraud.  The source of this category of information is: provided by the customer, except in the case of IP addresses which automatically provided by computers or devices interacting with our websites.</li>
                            <li>2.  Commercial Information:  Information concerning your parameters for seeking and/or offering offers for commercial real estate loans, including geographic, financial, sectoral, risk and other parameters; payment method and products and services purchased, obtained or considered; credit card numbers; debit card numbers; information regarding your interactions with an Finance Lobby website.  The purposes of collecting this category of information are: to provide you with the product or services you have requested; to provide browsing and matching services to other users; to help improve our products and services; to provide follow-up communications regarding your purchases; to market additional products and services you may be interested in; comply with legal obligations; and to prevent fraud.  The source of this category of information is: provided by the customer, or in the case of information regarding your interactions with an Finance Lobby website, automatically provided by computers or devices interacting with our websites.</li>
                            <li>3.  Internet or other electronic network activity information:  Browsing history, search history, and information regarding a consumer’s interaction with an internet website, application, or advertisement; web cookies, web beacons, and mobile AdIDs.  The purposes of collecting this category of information are: to provide you with the product or services you have requested; to help improve our products and services; to provide follow-up communications regarding your purchases; to market additional products and services you may be interested in; comply with legal obligations; and to prevent fraud.    The source of this category of information is:  automatically provided by computers or devices interacting with our websites.</li>
                            <li>4.  Geolocation data.  The source of this category of information is:  automatically provided by computers or devices interacting with our websites.  The purposes of collecting this category of information are: to provide you with the product or services you have requested; to help improve our products and services; to provide browsing and matching services to other users; to provide follow-up communications regarding your purchases; to market additional products and services you may be interested in; comply with legal obligations; and to prevent fraud.  If you do not want Finance Lobby to collect geolocation data, you can turn off location services in your browser or device.</li>
                            <li>5.  Professional or employment information.  The identity of your employer; contact information of your employer; level of experience in the industry.  The purposes of collecting this category of information are: to provide you with the products or services you requested; to provide browsing and matching services to other users; to help improve our products and services; to provide follow-up communications regarding your purchases; to market additional products and services you may be interested in; comply with legal obligations; and to prevent fraud.   The source of this category of information is: provided by the customer.</li>
                        </ul>

                        <p>Finance Lobby may use or disclose information in the Identifiers, Commercial Information, Internet or other electronic network activity information, Geolocation, and Professional or employment information data categories for a “business purpose” as defined in the California Consumer Privacy Act.  Business purposes may include providing our services to you and other users of the website; to provide browsing and matching services to other users; auditing related to a current interaction with a user; detecting security incidents, protecting against malicious, deceptive, fraudulent or illegal activity, and prosecuting those responsible for that activity; debugging errors in information technology systems that impair functionality; short-term, transient use; performing services such as maintaining or servicing accounts, providing customer service, processing or fulfilling orders and transactions, verifying customer information, processing payments, providing financing, providing advertising or marketing services, providing analytic services, or providing similar services on behalf of  Finance Lobby or a service provider; undertaking internal research for technological development and demonstration; and undertaking activities to verify or maintain the quality or safety of, or upgrade or enhance, Finance Lobby’s services.  Certain CCPA obligations do not apply when Personal Information is disclosed for a business purpose.</p>

                        <p>Finance Lobby may use pseudonymized and deidentified, and/or deidentified and aggregated, information in the Identifiers, Commercial Information, Internet or other electronic network activity information, Geolocation, and Professional or employment information data categories to create reports and analyses of market histories, conditions, and/or trends, which it may use for its own business purposes, share with others, publish, or sell.  Said reports and analyses will not contain any personal information that can reasonably identify, relate to, describe, be capable of being associated with, or be linked, directly or indirectly, to a particular consumer or any particular user.</p>

                        <p>Finance Lobby does not and has not collected data in the following categories:  Protected classes, biometric information, education information, profile inferences.</p>

                        <p>Finance Lobby does not knowingly collect personal information from persons 16 years of age or younger.</p>

                        <p>Right to Request Access to or Deletion of Personal Information (“Right to Be Forgotten”): You may have the right under the California Consumer Privacy Act to request information about the collection of your personal information by Finance Lobby, the sale/lease of the information, or access to the personal information itself.  This right may be exercised twice in any 12-month period.  Finance Lobby is obligated to provide this information only after receipt of a Verifiable Consumer Request.  You may also request deletion of any personal information retained by Finance Lobby.  If you wish to do any of these things, please contact Finance Lobby through the following <a href="/contact">link</a>, email Finance Lobby at <a href="mailto:Hello@financelobby.com">Hello@financelobby.com</a> and <a href="mailto:privacy@financelobby.com">privacy@financelobby.com</a>, or call Finance Lobby at <a href="tel:855-415-6229 (855-41LOBBY)">855-415-6229 (855-41LOBBY)</a>. You or your authorized agent must provide your name and postal address so we may locate any information we may have and process your request.  You will be asked to confirm any request to delete information.  Finance Lobby is not required to delete information that is necessary to complete the transaction for which the information was collected; provide a good or service requested by the Consumer or reasonably anticipated within the context of Finance Lobby’s ongoing relationship with the Consumer; or otherwise perform a contract between the Finance Lobby and the Consumer; to detect security incidents, protect against malicious, deceptive, fraudulent or illegal activity, or prosecute those responsible for that activity; to debug and to identify and repair information technology errors that impair functionality; or to comply with a legal obligation.</p>

                        <p>Finance Lobby does not sell or lease Personal Information to third parties, under the California Consumer Privacy Act.  Certain acts are not considered “sales,” including when (1) personal information is shared with a service provider that is contractually prohibited from using the personal information for any purpose beyond the service specifically requested (“service provider exception”), or (2) when the consumer has directed a company to disclose the personal information (“consumer directed exception”).</p>

                        <p>Right to Opt-Out of Sale/Lease of Personal Information (“Do Not Sell My Personal Information”):  Finance Lobby does not sell or lease Personal Information to third parties, under the California Consumer Privacy Act.</p>

                        <p>No Discrimination. Finance Lobby will not discriminate against any consumer for exercising their rights under the California Consumer Privacy Act.</p>
                    `,
                },
			}
		},
	})
</script>

