<template>
  <div class="page-basic">
    <BlockBasicText :data="basicContent" />
  </div>
</template>

<script lang="ts">
    import Vue from 'vue'
    import BlockBasicText from '@/components/blocks/BlockBasicText.vue'
	export default Vue.extend({
		name: 'BasicPage',
		components: {
            BlockBasicText,
		},
		data() {
			return {
                page: 'basic-page',
                basicContent: {
                    title: 'FINANCE LOBBY TERMS AND CONDITIONS',
                    text: `
                        <p>Last Updated: September 23, 2020</p>
                        <p>These terms and conditions apply to all users of this Finance Lobby website (the “Site”). Before using this website, please review the following legal terms and conditions and the terms of our online Privacy Policy, which are incorporated herein by reference (collectively referred to as “Terms of Use” or the “Agreement”). By accessing and using this website for any purpose you agree to be bound by the Terms of Use. If you do not agree with these Terms of Use, you may not access or otherwise use this website.</p>
                        <h4>Nature of the Finance Lobby Website</h4>
                        <p>The website provides a convenient forum for matching potential lenders with potential borrowers in the commercial real estate sector.   Finance Lobby is not a lender, broker, investor, financial service provider, advisor or consultant.  Finance Lobby is not acting as an agent or partner of any party.  Finance Lobby is not a party to any transaction between potential lenders and potential borrowers.  Any transaction between potential lenders and potential borrowers takes place between those parties, off-site, without any involvement by Finance Lobby.  Any offer to enter into a transaction is solely the responsibility of the offering party.  You agree that Finance Lobby is not responsible for verifying the suitability, legality, or terms of any offer, and does not guarantee that any party will complete a proposed transaction.</p>
                        <h4>Use of the Website</h4>
                        <p>Finance Lobby grants you a limited right to use this website for your personal use only.   You may access and view the content on the website on your computer or other Internet compatible device, including mobile devices and tablets, and make single copies or prints of the content on the website for your personal use only. </p>
                        <p>You agree to comply with all applicable laws, statutes and regulations regarding use of the website.  You agree not to use the website or any content or information therein for any unlawful purpose.</p>
                        
                        <p>You warrant and represent that any information you submit to the website is accurate and complete.  You warrant and represent that you are using truthful identification and contact information in creating your profile for this website, and that you are not creating a profile under an alias, fictitious identity, or under the information of a third party without their consent.   </p>
                        <p>You agree not to harvest, scrape, or automatically retrieve and store any information on this website.  You agree not to copy or repurpose any information on this website for use on another website, app, blog, product or service.   You may not exploit any aspect of the site or information thereon for any commercial purposes not expressly permitted by Finance Lobby.</p>
                        <p>You agree not to share personal information including name, phone number, street address, or email address with any other user until after a quote is accepted. Failure to adhere to this rule can lead to the user being banned from the Finance Lobby platform.</p>

                        <h4>Use by Children</h4>
                        <p>The website is not intended for users under the age of 18 and parents or guardians may not agree to the Terms of Use on their behalf. Finance Lobby does not knowingly collect personal identifiable information from users under the age of 18. Such users are expressly prohibited from submitting their personally identifiable information to us; any information submitted by such users will not knowingly be used, posted or retained by us.</p>
                        <h4>Intellectual Property</h4>
                        <p>Any and all text, images, designs, marks, and other content of this website originated from Finance Lobby are copyrighted, trademarked, protected by trade dress or otherwise proprietary to Finance Lobby.  Any rights not expressly granted herein are reserved.  All third-party product names, trademarks and registered trademarks that may appear on Finance Lobby are property of their respective owners.</p>
                        <p>Finance Lobby provides the following notice pursuant to the Digital Millennium Copyright Act of 1998 (the “DMCA”).  Finance Lobby requires that users of our website respect the intellectual property rights of others.  It is Finance Lobby’s policy, in appropriate circumstances, to terminate the accounts of users, members, or others who are repeat infringers or are repeatedly charged with infringement.</p>
                        <p>If you believe that anything on our website infringes a copyright that you own or control, you may notify our Designated Agent by email to <a href="mailto:Hello@financelobby.com">Hello@financelobby.com</a> and <a href="mailto:privacy@financelobby.com">privacy@financelobby.com</a>.  Your notice must include ALL of the following information to be processed.</p>
                        <ul>
                            <li>The electronic or physical signature of the owner of the copyright or the person authorized to act on the owner's behalf;</li>
                            <li>Identification of the copyrighted work claimed to have been infringed, or a representative list of such works;</li>
                            <li>The URL or Internet location of the materials claimed to be infringing or to be the subject of infringing activity, or information reasonably sufficient to permit us to locate the material;</li>
                            <li>Your name, address, telephone number and email address;</li>
                            <li>A statement by you that you have a good faith belief that the disputed use of the material is not authorized by the copyright owner, its agent or the law; and</li>
                            <li>A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or are authorized to act on the copyright owner's behalf.</li>
                        </ul>
                        <p>If you believe that anything on our website infringes a non-copyright intellectual property right, such as a trademark, please notify us by email to <a href="mailto:Hello@financelobby.com">Hello@financelobby.com</a> and <a href="mailto:privacy@financelobby.com">privacy@financelobby.com</a>, including all relevant information including identification of the intellectual property right and the URL of the allegedly infringing material.</p>
                        <h4>Submitted Content</h4>
                        <p>By uploading or submitting any photos, text, audio, video, messages, information, or any other content for use on this website (“Submitted Content”), you grant to Finance Lobby a royalty-free, non-exclusive, worldwide, irrevocable right in any existing or future media, known or unknown, now or at any later date and license to use, reproduce, perform, display, distribute, adapt, modify, re-format, create derivative works of, and otherwise commercially or non-commercially exploit in any manner, any and all of the Submitted Content, subject to the Privacy Policy.  </p>
                        <p>You warrant and represent that you have the rights to submit your Submitted Content for use on the Finance Lobby site.  You warrant and represent that your Submitted Content does not infringe the intellectual property rights of any third party.  You agree that you will not submit any content that is unlawful, false, misleading, abusive, libelous, harassing, obscene, or discriminatory.   You agree to indemnify, defend, and hold Finance Lobby harmless from all claims, causes of action, allegations, costs, expenses, fees (including reasonable attorneys’ fees), judgments, liabilities, losses, and damages arising from or relating to your Submitted Content and any breach of your warranties and representations.</p>
                        <p>We do not routinely screen, edit, or review Submitted Content. However, Finance Lobby reserves the right to remove any Submitted Content from the site, at its sole discretion, including for any violation of these Terms and Conditions, without notice. </p>
                        <h4>Third-Party Subscribers; Accuracy of Information</h4>
                        <p>Finance Lobby is exclusively a communication service between potential borrowers and potential lenders.  Although Finance Lobby displays information supplied by users and facilitates contact between users, such actions do not in any way imply, suggest, or constitute Finance Lobby’s sponsorship, agency, partnership or approval of any user, or any affiliation whatsoever between Finance Lobby and any user.   Finance Lobby makes no warranty that information submitted by users is not inaccurate, incomplete or out of date.   Users submitting information have sole responsibility for the accuracy and completeness, and/or usefulness of their submitted information.</p>
                        <h4>Links</h4>
                        <p>The Finance Lobby website may contain links to third-party websites.  Links to other websites are provided for your convenience and a link does not imply endorsement of, sponsorship of, or affiliation with a linked site by Finance Lobby.  Finance Lobby does not control these other websites and cannot be responsible for the content or accuracy of the information or other material on these websites.  Finance Lobby is not responsible for the contents of any linked site and does not warrant, represent, or assume responsibility or liability for the accuracy, security, completeness, or operation of any linked site or any information or other materials downloaded from or contained on or in any linked site.  Before using other websites or disclosing personal information to them, you should examine the terms and conditions of those websites, as they may differ from the Finance Lobby website.</p>
                        <h4>Subscription Terms</h4>
                        <p>Finance Lobby is a paid subscription service.  These Terms of Use govern your subscription on Finance Lobby, including without limitation the Disclaimer/Limitation of Liability, Indemnification, and Dispute Resolution sections.    These terms and plans may change from time to time.  You will be informed of any change in the subscription price, renewal terms, or other terms and will have the opportunity to cancel your subscription. </p>
                        <p>By purchasing a subscription, you are enrolling in a recurring payment program.   You authorize Finance Lobby to charge the PayPal, credit card, debit card, or other financial account associated with your Finance Lobby account for the monthly subscription fee, and any applicable taxes, with your consent, according to the subscription terms applicable at that time.</p>
                        <p>The term of the service is one month, automatically billed in advance on or about the 1st day of the preceding month, automatically renewing for an ensuing month, unless it is cancelled prior to billing for the renewal term.  You must cancel your subscription before it renews in order to avoid billing of subscription fees for the renewal term.   Subscriptions rates are subject to change, but you will be notified of any changed rate with the option to cancel as provided by these Terms of Use.   You may cancel at any time through the Account function of the website or contact our customer service department at <a href="mailto:Hello@financelobby.com">Hello@financelobby.com</a>, <a href="mailto:privacy@financelobby.com">privacy@financelobby.com</a> and <a href="tel:855-415-6229 (855-41LOBBY)">855-415-6229 (855-41LOBBY)</a>.  Subscription fees are non-refundable.  Finance Lobby may in its sole discretion offer reduced-fee or free subscriptions for promotional purposes. </p>
                        <p>If Finance Lobby is unable to complete a fee transaction when due, Finance Lobby may suspend or cancel your subscription until payment is made successfully.</p>
                        <p>Each subscription and the rights and privileges provided to a subscriber is personal and non-transferable.  All sales and payments of subscription fees will be in US Dollars.  If your purchase of a subscription is subject to sales tax, VAT, or similar tax charged at the point of sale, you authorize Finance Lobby to add the amount of such tax to any charge for your subscription.  </p>
                        <p>Finance Lobby may, in its sole discretion, cancel your subscription at any time for violation of these Terms & Conditions, breach of warranty/representation, misuse of the website, or for any other reason.</p>
                        <h4>Disclaimer/Limitation of Liability</h4>
                        <p>The Finance Lobby website, its content, and any information available on or through the website are provided “as is” and “as available” and without any representations or warranties of any kind, to the fullest extent permitted pursuant to applicable laws, of accuracy, reliability, title, merchantability, non-infringement, fitness for a particular purpose or any other warranty, condition, guarantee or representation, whether oral, in writing or in electronic form, including but not limited to the accuracy or completeness of any information contained therein or provided by the website.</p>
                        <p>Finance Lobby does not represent or warrant that access to the Finance Lobby website will be uninterrupted or that there will be no failures, errors or omissions or loss of transmitted information, or that no viruses will be transmitted. Without limitation, Finance Lobby does not warrant the accuracy or completeness of any information included in any profile or other information created or provided through the website.  Finance Lobby does not sponsor, vouch for, or act as the agent or partner of, any user of this site for any purpose.  Users are solely responsible for ensuring the accuracy of all information provided and Finance Lobby shall undertake no responsibility for damages caused by the inclusion of erroneous, incomplete or outdated information by users.</p>
                        <p>The users of this website are independent contractors and not agents or employees of Finance Lobby.  Finance Lobby’s display through the website of information of such parties does not in any way imply, suggest, or constitute any sponsorship, control or approval by Finance Lobby of such party or any affiliate of such party. You agree that Finance Lobby is in no way responsible for the accuracy, timeliness, or completeness of information it may obtain from these subscribers. Your interaction with such subscribers is at your own risk. Finance Lobby will have no liability for the acts, errors, omissions, representations, warranties, breaches or negligence of any such subscribers or for any personal injuries, death, property damage, loss of business opportunity, loss of prospective advantage, loss of investment, or any other damages or expenses of any kind or nature resulting therefrom.</p>
                        <p>You agree that Finance Lobby shall not be responsible or liable for any borrowing, lending and/or investment decisions based on information obtained from this site.</p>
                        <p>Finance Lobby and its affiliates have no liability and will make no refund in the event of any delay, cancellation, strike, force majeure, or other causes beyond our direct control. Finance Lobby shall not be liable to you or any third parties for any direct, indirect, special, consequential or punitive damages allegedly sustained arising out of this agreement or the use of the website, including but not limited to: the providing of services hereunder, the delivery or non-delivery of information, the sale or purchase of any goods or service, your access to or inability to access the website, including for viruses alleged to have been obtained from the website, your use of or reliance on the service or any of the merchandise, information or materials available on the website, regardless of the type of claim or the nature of the cause of action, even if advised of the possibility of such damages.</p>
                        <p>Some states do not allow the exclusion of implied warranties or the limitation or exclusion of liability for incidental or consequential damages, so the above exclusions or limitations may not apply to you. You may also have other rights that vary from state to state.  If the foregoing limitations are held inapplicable or unenforceable for any reason, you agree that the maximum liability of Finance Lobby to you for any type of damages shall be limited to U.S. $50.00.</p>
                        <h4>Indemnification</h4>
                        <p>You agree to indemnify, defend, and hold Finance Lobby harmless from all claims, causes of action, allegations, costs, expenses, fees (including reasonable attorneys’ fees), judgments, liabilities, losses, and damages arising from or relating to your use of the Finance Lobby website, your provision or non-provision of services, claims of tort, contract, premises liability arising from your services and use of this website, and any breach of your warranties and representations.</p>
                        <h4>Dispute Resolution</h4>
                        <h5>I. General Information</h5>
                        
                        <p>Finance Lobby is committed to customer satisfaction, so if you have a problem or dispute, Finance Lobby will try to resolve it with a neutral and cost-effective means of resolving the dispute or claim quickly. Accordingly, you and Finance Lobby agree that we will resolve any claim or dispute at law or equity relating in any way to the website, any information, services or products provided by us, any representations made by us, or the Terms of Use (each, a “Claim”) in accordance with one of the subsections below or as Finance Lobby and you otherwise agree in writing. Before resorting to these alternatives, we strongly encourage you to first contact us directly to seek a resolution.  These Dispute Resolution terms shall survive any termination of this Agreement.</p>
                        <h5>II. Law and Place of Dispute</h5>
                        <p>These Terms of Use are governed by and will be construed according to the laws of the State of Delaware in any proceeding or legal process, without regard to any conflict of law provisions. You agree that any permitted lawsuit may be brought only in the state or federal courts seated in Delaware, and in using this website, you consent to jurisdiction of such courts for the purpose of litigating such actions.</p>
                        <h5>III. Arbitration</h5>
                        <p>Any Claim (excluding claims for injunctive or other equitable relief) shall be resolved exclusively by binding non-appearance-based arbitration pursuant to the Commercial Arbitration Rules (“AAA Rules”) of the American Arbitration Association (“AAA”). The arbitration will take place in Delaware. Part or all of the arbitration may be conducted by telephone or based on written submissions, and will not require the personal appearance of the parties or any witnesses unless otherwise agreed by the parties. The allocation of costs and fees for such arbitration shall be determined in accordance with AAA Rules. The arbitration shall be conducted by a single, neutral arbitrator who shall be appointed by the AAA. The arbitrator’s decision and award shall be final and binding and may be entered in any court with jurisdiction. Nothing in these Terms of Use will prevent a party from seeking injunctive or other equitable relief with respect to the infringement, misappropriation or other violation of such party’s intellectual property or other proprietary rights in any court of competent jurisdiction. In the event the foregoing agreement to arbitrate is deemed unlawful, void, or for any reason unenforceable with respect to any claim, dispute or controversy, then you agree that any Claim, shall be filed and adjudicated only in the state and federal courts located in or having jurisdiction in Delaware and you hereby irrevocably and unconditionally consents and submits to the exclusive jurisdiction of such courts over any suit, action or proceeding arising out of this Agreement.</p>
                        <h5>IV. No Class Actions</h5>
                        <p>Any and all proceedings to resolve a Claim will be conducted only on an individual basis and not in a class, joint, consolidated or representative action or arbitration. If for any reason a Claim proceeds in a court rather than in arbitration we each waive the right to a jury trial. The Federal Arbitration Act and federal arbitration law apply to these Terms of Use. Any arbitration decision may be confirmed by any court with competent jurisdiction.</p>
                        <h4>Modifications to these Terms of Use</h4>
                        <p>Finance Lobby reserves the right to make changes to the Terms of Use or any related policies or practices, in its sole discretion, without specific notice to you. You should therefore review this page from time to time for updated information. Any changes to the Terms of Use will be posted to this website.</p>
                        <p>These Terms and Conditions, along with any documents expressly incorporated therein, constitute the entire and only agreement between you and Finance Lobby  with respect to your use of the Finance Lobby site and supersedes all prior or contemporaneous agreements, representations, warranties and/or understandings with respect to your use of the Finance Lobby site.</p>
                    `,
                },
			}
		},
	})
</script>